import { toggleProduct, updateVariantStock } from '@/app/admin/actions';
import { createClient } from '@/lib/supabase/server';
import { formatMoney } from '@/lib/utils/money';

export default async function ProductsPage() {
  const supabase = await createClient();
  const { data: products } = await supabase.from('products').select('id, name_fr, slug, base_price, currency_code, is_active, is_featured, product_variants(id, sku, size_label, color_name_fr, stock_quantity, low_stock_threshold, is_active)').is('deleted_at', null).order('sort_order');
  return <div className="admin-page"><header className="admin-heading"><div><p>CATALOGUE</p><h1>Produits & stock.</h1><span>La boutique reste nette, le stock reste vrai.</span></div></header><section className="admin-panel"><div className="admin-panel-title"><div><p>INVENTAIRE</p><h2>{products?.length ?? 0} pièces au catalogue</h2></div></div><div className="admin-products">{products?.map((product) => <article key={product.id}><div className="product-title"><div><h3>{product.name_fr}</h3><p>/{product.slug} · {formatMoney(Number(product.base_price), product.currency_code)}</p></div><form action={toggleProduct}><input type="hidden" name="id" value={product.id} /><input type="hidden" name="active" value={String(!product.is_active)} /><button className={product.is_active ? 'pill pill-live' : 'pill'}>{product.is_active ? 'En ligne' : 'Masqué'}</button></form></div><div className="variants">{(Array.isArray(product.product_variants) ? product.product_variants : []).map((variant) => <form key={variant.id} action={updateVariantStock}><input type="hidden" name="id" value={variant.id} /><span>{variant.color_name_fr} · {variant.size_label}<small>{variant.sku}</small></span><input aria-label={`Stock ${variant.sku}`} name="stock" type="number" min="0" defaultValue={variant.stock_quantity} className={variant.stock_quantity <= variant.low_stock_threshold ? 'low-stock' : ''}/><button>Enregistrer</button></form>)}</div></article>)}</div></section></div>;
}
