project_id = "pukvrerdloudfiphomsj"

[db]
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[storage.buckets.product-images]
public = true

[storage.buckets.site-assets]
public = true
