import { removePromotion, setPromotion } from '@/app/admin/actions';
import { createClient } from '@/lib/supabase/server';
import { formatPrice } from '@/lib/utils/money';

export default async function PromotionsPage() {
  const supabase = await createClient();
  const { data: products } = await supabase.from('products').select('id, name_fr, base_price, compare_at_price, currency_code, product_collections(collections(slug))').is('deleted_at', null).order('name_fr');
  const promoProducts = (products ?? []).filter(product => (Array.isArray(product.product_collections) ? product.product_collections : []).some(link => Array.isArray(link.collections) ? link.collections[0]?.slug === 'promotions' : link.collections?.slug === 'promotions'));
  const regularProducts = (products ?? []).filter(product => !promoProducts.some(promo => promo.id === product.id));
  return <div className="admin-page"><header className="admin-heading"><div><p>VENTE</p><h1>Promotions.</h1><span>Les prix normaux restent dans les fiches produits. Ici, tu ajoutes une offre puis tu la retires quand c’est fini.</span></div></header><section className="admin-panel create-product-panel"><div className="admin-panel-title"><div><p>NOUVELLE PROMOTION</p><h2>Ajouter un article</h2></div></div><form action={setPromotion} className="product-edit-form"><label>Article<select name="product_id" required><option value="">Choisir un article</option>{regularProducts.map(product => <option key={product.id} value={product.id}>{product.name_fr} — {formatPrice(Number(product.base_price), product.currency_code)}</option>)}</select></label><label>Prix promotionnel FCFA<input name="promotion_price" type="number" min="0" required/></label><button className="admin-primary-button">Ajouter à la promo</button></form></section><section className="admin-panel"><div className="admin-panel-title"><div><p>EN COURS</p><h2>{promoProducts.length} article{promoProducts.length > 1 ? 's' : ''} en promotion</h2></div></div><div className="promotion-list">{promoProducts.map(product => <form key={product.id} action={removePromotion}><div><strong>{product.name_fr}</strong><span>Prix promo : {formatPrice(Number(product.base_price), product.currency_code)}</span></div><button>Retirer la promotion</button><input type="hidden" name="product_id" value={product.id}/></form>)}{!promoProducts.length && <p className="admin-empty">Aucune promotion active.</p>}</div></section></div>;
}
