import { updateOrderStatus } from '@/app/admin/actions';
import { createClient } from '@/lib/supabase/server';
import { formatMoney } from '@/lib/utils/money';

const labels: Record<string, string> = { pending: 'À confirmer', confirmed: 'Confirmée', preparing: 'Préparation', ready: 'Prête', delivered: 'Livrée', cancelled: 'Annulée' };
export default async function OrdersPage() {
  const supabase = await createClient();
  const { data: orders } = await supabase.from('orders').select('id, order_number, status, total, currency_code, customer_note, created_at, customers(full_name, phone, whatsapp_phone), order_items(product_name, size_label, quantity)').order('created_at', { ascending: false });
  return <div className="admin-page"><header className="admin-heading"><div><p>OPÉRATIONS</p><h1>Commandes.</h1><span>Confirme, prépare, livre. Rien ne se perd.</span></div></header><section className="admin-panel"><div className="admin-panel-title"><div><p>SUIVI EN DIRECT</p><h2>{orders?.length ?? 0} commande{(orders?.length ?? 0) > 1 ? 's' : ''}</h2></div></div>{orders?.length ? <div className="admin-orders">{orders.map((order) => { const customer = Array.isArray(order.customers) ? order.customers[0] : order.customers; const items = Array.isArray(order.order_items) ? order.order_items : []; return <article key={order.id}><div className="order-top"><div><span>#{order.order_number}</span><h3>{customer?.full_name || 'Client'}</h3><p>{customer?.whatsapp_phone || customer?.phone || 'Coordonnées à renseigner'}</p></div><strong>{formatMoney(Number(order.total), order.currency_code)}</strong></div><p className="order-items">{items.map((item) => `${item.quantity}× ${item.product_name}${item.size_label ? ` · ${item.size_label}` : ''}`).join(' — ') || 'Articles à renseigner'}</p>{order.customer_note && <p className="order-note">“{order.customer_note}”</p>}<form action={updateOrderStatus}><input type="hidden" name="id" value={order.id} /><select name="status" defaultValue={order.status}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button>Mettre à jour</button></form></article>; })}</div> : <div className="admin-empty">Le tableau est prêt : les commandes WhatsApp viendront se ranger ici.</div>}</section></div>;
}
