import Image from 'next/image';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';

export default async function CollectionsPage() {
  const supabase = await createClient();
  const { data: collections } = await supabase.from('collections').select('id, slug, name_fr, description_fr, image_url').eq('is_active', true).neq('slug', 'promotions').order('sort_order');
  return <main className="relative min-h-screen overflow-hidden bg-background px-5 py-10 text-foreground md:px-8"><div className="pointer-events-none absolute -right-28 top-10 h-96 w-96 rounded-full bg-brand-accent/20 blur-3xl"/><div className="relative mx-auto flex max-w-7xl flex-col gap-10"><section className="rounded-[3rem] bg-brand-evergreen p-8 text-white shadow-[0_30px_90px_rgba(15,59,46,0.22)] md:p-12"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-brand-accent">Collections</p><h1 className="mt-5 max-w-5xl text-5xl font-semibold leading-[0.92] tracking-[-0.06em] md:text-7xl">Choisir un univers, trouver la bonne pièce.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-white/72">Les collections sont composées depuis le studio de la maison.</p></section><section className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{collections?.map(collection => <Link key={collection.id} href={`/catalogue?collection=${collection.slug}`} className="group relative min-h-[320px] overflow-hidden rounded-[2.5rem] bg-brand-evergreen p-7 text-white shadow-[0_24px_80px_rgba(80,34,28,0.10)] transition duration-300 hover:-translate-y-1 md:p-8">{collection.image_url && <Image src={collection.image_url} alt={collection.name_fr} fill sizes="(max-width: 768px) 100vw, 25vw" className="object-cover opacity-65 transition duration-500 group-hover:scale-105"/>}<div className="absolute inset-0 bg-gradient-to-t from-brand-evergreen via-brand-evergreen/35 to-transparent"/><div className="relative flex h-full flex-col justify-end"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-brand-accent">Collection</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em]">{collection.name_fr}</h2><p className="mt-3 text-sm leading-6 text-white/75">{collection.description_fr || 'Découvrir la sélection.'}</p><span className="mt-6 inline-flex w-fit rounded-full bg-white/20 px-5 py-3 text-sm font-semibold backdrop-blur">Explorer</span></div></Link>)}</section></div></main>;
}
